### ISSUE TITLE
Vipyrsec Site - MVP

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [vipyrsec/vipyrsec-site#1]
- [x] Populate About section.
- [x] Add projects content. 
- [x] Add blog content and remove placeholders.
- [x] ~Add docs endpoint.~ Bikeshed.
- [x] ~Add contact form.~ Bikeshed
- [x] Scrub any unused template content and replace with appropriate content or remove. (CTRL+F my beloved.) 
- [x] Remove dead routes so SEO doesn't pick up weird stuff. 
- [x] ~Update Readme with publishing/branding guide?~ Internal, unnecessary. 

@shenanigansd 
- [x] Add Github Workflow.
- [x] Add branch protection and whatnot. 
- [x] Make repo public.
- [x] CI/CD tasks.

**Comment by shenanigansd** [comment]
Reference: https://docs.astro.build/en/guides/deploy/github/
